# Site settings
title: Martin Deubzer
email: deubzerm@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Blog about Paragliding, Kiteboarding and other stuff related to me.
baseurl: "" # the subpath of your site, e.g. /blog/

url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: mtdz7
github_username:  deubzerm

# Build settings
markdown: kramdown

excerpt_separator: <!--more-->

gems: [jekyll-paginate]

paginate: 5
paginate_path: "/blog/page:num/"
